### ISSUE TITLE
rviz窗口不显示？

### ISSUE THREAD

**Issue by baibai09** [SlamCabbage/NDTMC-LIO-SAM#1]
你好，我简单地测试了一下，跑bag包的时候，这个rviz没有显示。另外，我还没播放bag，这个time of loop 怎么就运行起来了？

![111](https://github.com/SlamCabbage/NDTMC-LIO-SAM/assets/138378838/436c5483-9056-4b56-8fc8-ab9e3d37b262)
![113](https://github.com/SlamCabbage/NDTMC-LIO-SAM/assets/138378838/4233e03e-5b3f-4022-9c8a-be78c8c9ea97)

![112](https://github.com/SlamCabbage/NDTMC-LIO-SAM/assets/138378838/9fda684e-596c-4d17-9a06-fffe151eade1)

**Comment by SlamCabbage** [comment]
重新开个终端打开rviz就行，
如果是在当前project的位置那么：rviz -d src/NDTMC-LIO-SAM/launch/include/config/rviz.rviz

这个time of loop之所以会在一开始就进行显示，是因为处理回环使用的是一个独立线程，启动程序就会开始执行。
