### ISSUE TITLE
关于雷达设置

### ISSUE THREAD

**Issue by JiangWeiHn** [SlamCabbage/NDTMC-LIO-SAM#3]
请问我的激光雷达设置扫描范围为-10°到200°左右，能用这个方法建图么？我看论文好像要设置为360°，是必要条件么？

**Comment by SlamCabbage** [comment]
> 请问我的激光雷达设置扫描范围为-10°到200°左右，能用这个方法建图么？我看论文好像要设置为360°，是必要条件么？

liosam应该是可以的，但是回环检测部分需要你先把360度范围场景恢复后再使用

**Comment by JiangWeiHn** [comment]
收到，谢谢
